services:
  - type: web
    name: feedback-api
    env: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: ./apps/api


  # - type: web
  #   name: feedback-web
  #   env: image
  #   image:
  #     url: docker.io/yashv97/acowale-feedback:web-latest
  #   envVars:
  #     - key: VITE_API_URL
  #       fromService:
  #         type: web
  #         name: feedback-api
  #         property: url

  - type: redis
    name: feedback-redis
    ipAllowList: []
    plan: free

databases:
  - name: feedback-db
    databaseName: feedback_db
    user: feedback_user
    plan: free
